In [ ]:
# Importamos todas las librerias
import pandas as pd
import numpy as np

In [ ]:
# Definir los datos de las 8 personas
data = {
    "Nombre": ["Ana", "Carlos", "Beatriz", "David", "Elena", "Francisco", "Gabriela", "Héctor"],
    "Profesión": ["Ingeniera", "Doctor", "Abogada", "Profesor", "Arquitecta", "Escritor", "Chef", "Músico"],
    "País": ["España", "México", "Brasil", "Argentina", "Chile", "Colombia", "Perú", "Ecuador"]
}

# Crear el DataFrame
df_personas = pd.DataFrame(data)

# Imprimir el DataFrame
print(df_personas)


      Nombre   Profesión       País
0        Ana   Ingeniera     España
1     Carlos      Doctor     México
2    Beatriz     Abogada     Brasil
3      David    Profesor  Argentina
4      Elena  Arquitecta      Chile
5  Francisco    Escritor   Colombia
6   Gabriela        Chef       Perú
7     Héctor      Músico    Ecuador


In [ ]:
#Leyendo un archivo de tipo csv
df = pd.read_csv('data.csv')
print(df)

     Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [ ]:
# muestra los 5 primeros registros del dataframe
df.head()

Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
# Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar
# un resumen estadístico de los datos.
import pandas as pd
df_random = pd.DataFrame(np.random.rand(100,8))
df_random.head(10)


0         1         2         3         4         5         6  \
0  0.090490  0.359119  0.622381  0.138386  0.215414  0.623441  0.488430   
1  0.372660  0.696794  0.362954  0.958181  0.451620  0.190741  0.136658   
2  0.582907  0.742757  0.251165  0.346836  0.821524  0.738280  0.324599   
3  0.156131  0.666754  0.573221  0.813406  0.927856  0.401862  0.974903   
4  0.952361  0.708484  0.952579  0.476867  0.004546  0.943811  0.449035   
5  0.181463  0.525941  0.272019  0.531656  0.872228  0.915881  0.155056   
6  0.679975  0.590085  0.260035  0.600362  0.253493  0.938701  0.501245   
7  0.923421  0.035831  0.689383  0.709749  0.470999  0.218393  0.335203   
8  0.212824  0.077597  0.569801  0.262434  0.781399  0.357083  0.888310   
9  0.985232  0.695633  0.292114  0.668192  0.144646  0.761617  0.804914   

          7  
0  0.497214  
1  0.948432  
2  0.756379  
3  0.131084  
4  0.760599  
5  0.615681  
6  0.190966  
7  0.531166  
8  0.308709  
9  0.254632

In [ ]:
# Resumen estadistico de los datos
df_random.describe()

0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.534660    0.518145    0.498168    0.476642    0.477764    0.546323   
std      0.297382    0.286461    0.271947    0.271768    0.304140    0.262807   
min      0.009654    0.009558    0.048657    0.006387    0.004546    0.041658   
25%      0.275084    0.282880    0.269023    0.234542    0.216128    0.289675   
50%      0.587786    0.549813    0.497423    0.468038    0.457439    0.577403   
75%      0.772055    0.754105    0.712454    0.653806    0.739016    0.771067   
max      0.995674    0.992233    0.994054    0.999490    0.998682    0.987090   

                6           7  
count  100.000000  100.000000  
mean     0.494782    0.408517  
std      0.296802    0.285140  
min      0.016676    0.002932  
25%      0.250493    0.155006  
50%      0.480406    0.349815  
75%      0.778131    0.612328  
max      0.998303    0.966097

Parte 2

In [ ]:
# Crear un array de números del 1 al 10
# mostrar la suma, la media, y el valor máximo.

In [ ]:
array=np.arange(1,11)
print(array)
suma = np.sum(array)
print("Suma:", suma)
media = np.mean(array)
print("Media:", media)
maximo = np.max(array)
print("Máximo:", maximo)



[ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Máximo: 10


In [ ]:
# Crear un array de 3x4 lleno de ceros
#y luego cambiar su forma a 2x6
array_ceros = np.zeros((3, 4))
print("Array original:\n", array_ceros)
array_modificado = array_ceros.reshape(2, 6)
print("\nArray modificado:\n", array_modificado)

Array original:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array modificado:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
matriz_aleatoria = np.random.rand(3, 3)
print("Matriz aleatoria:\n", matriz_aleatoria)
matriz_transpuesta = matriz_aleatoria.T
print("\nMatriz transpuesta:\n", matriz_transpuesta)



Matriz aleatoria:
 [[0.95745767 0.37168556 0.53745235]
 [0.9513219  0.34369147 0.93925936]
 [0.27584216 0.89457728 0.86327537]]

Matriz transpuesta:
 [[0.95745767 0.9513219  0.27584216]
 [0.37168556 0.34369147 0.89457728]
 [0.53745235 0.93925936 0.86327537]]


In [ ]:
# concatenar dos arrays
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([6, 7, 8, 9, 10])
array_concatenado = np.concatenate((array_1, array_2))
print (array_concatenado)

[ 1  2  3  4  5  6  7  8  9 10]
